### ISSUE TITLE
tillezone reset when write cfg

### ISSUE THREAD

**Issue by Skysosaurus** [shred86/Ortho4XP#24]
V1.40.03  When save tile config the zonelist var is empty.

I try to modify O_Config_Utils.py line 1121
      if lat in _zone_list and lon+1 in _zone_list:
to 
      if lat in _zone_list and lon in _zone_list:
It seems to work fine now with this modification.

Bravo for your work (and oscarpilot to)

**Comment by shred86** [comment]
Hm, I'm not able to replicate this. What are the coordinates of the tile you were having issues with?

The `lon+1` is needed because the tile coordinates are for the southwest corner of the tile, so anything to the east (right) of that corner is going to be the longitude of the tile coordinates +1.
