### ISSUE TITLE
Bug: install_mac.sh not found

### ISSUE THREAD

**Issue by scriptPilot** [shred86/Ortho4XP#27]
Thanks for your efforts to maintain Ortho4XP!

I would like to install on MacOS, but after installing Homebrew, I get the following issue, probably because the *install_mac.sh* file is not part of the downloaded full installation zip.

Screenshot:

<img width="263" alt="Bildschirmfoto 2024-06-29 um 09 45 48" src="https://github.com/shred86/Ortho4XP/assets/19615586/9a5dcb89-f452-4de5-9450-f6234f21e2f7">

**Comment by scriptPilot** [comment]
When I manually download and add the file to the *_internal* folder, I get the following error:

````
Error!
 
install_mac.sh must be located in the main Ortho4XP directory.
````

**Comment by scriptPilot** [comment]
Looking into the code I think the root cause are missing files in the downloaded zip. Adding the following files manually to the *_insternal* folder are solving the issue for me:

<img width="211" alt="Bildschirmfoto 2024-06-29 um 09 57 12" src="https://github.com/shred86/Ortho4XP/assets/19615586/78ccb78c-f53f-4f2d-a665-7b51a0f47f6d">

**Comment by shred86** [comment]
If you're trying to setup Ortho4XP "manually" (i.e. not use the bundled version), you should be cloning this repository, not downloading the bundled version.

The installation instructions are broken up into two sections, the [Recommended setup](https://github.com/shred86/Ortho4XP/wiki/Installation#recommended-setup), which is the bundled version that doesn't require using install_mac.sh, and the [Manual setup](https://github.com/shred86/Ortho4XP/wiki/Installation#manual-setup), which is where you would use install_mac.sh.

So the first question is, do you want to use the bundled version? If so, follow the steps in the Recommended setup. 

If you're trying to do the manual setup, follow those steps.

**Comment by scriptPilot** [comment]
Ah perfect, thanks for your detailed response.
It works now like a charm on MacOS via MacBook M1 :-)
